/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://3hisfcaeuvbtrl4zsvrfx6smby.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-o5in5qvpqne63bdsrkpowyujly",
    "aws_cognito_identity_pool_id": "us-east-1:0528d3a0-5974-4fb6-8334-0bdb78ab9627",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8NqHXd03s",
    "aws_user_pools_web_client_id": "206su04qr9kg5gi9h1pbff05ko",
    "oauth": {},
    "aws_user_files_s3_bucket": "sam6f16f2f46a8a452b96efa0d22a9e16c0120558-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
